"""TTD authoritative 2D-geometry core (spec §12.1).

Chunk 1 populates this subpackage: parameters/dials (:mod:`.params`), op counters
(:mod:`.counters`), geometry primitives (:mod:`.geometry`), the shape library
(:mod:`.shapes`), and the C7 dial-consistency check (:mod:`.dials`). The nester,
``N(S, r)`` / ``η``, and the streams/refiner are later chunks.
"""

from __future__ import annotations

from .counters import CKind, OpCounter
from .dials import (
    C7Report,
    brunn_minkowski_lhs,
    brunn_minkowski_ok,
    dial_consistency,
    occupancy_rule_ok,
    phi_f,
    phi_i,
    phi_occupancy,
)
from .geometry import (
    AntipodalPair,
    GeometryError,
    Vertices,
    antipodal_edge_pairs,
    aspect_ratio,
    convex_decompose,
    convexity_defect,
    count_reflex_vertices,
    has_admissible_antipodal_pair,
    ifp,
    inflate,
    inflated_area,
    inflated_area_approx,
    interior_disjoint,
    min_edge_length,
    minkowski_sum_convex,
    nfp,
    normalize_ccw,
    reflect,
    region_vertices,
    sample_boundary,
    signed_area,
    snap,
    to_polygon,
    to_vertices,
    within_container,
)
from .nesting import (
    Label,
    LabelResult,
    NesterConfig,
    NestResult,
    NestStatus,
    Placement,
    label_candidate,
    nest,
    packing_margin_radius,
    packs,
    verify_placements,
)
from .params import (
    BUFFER_QUAD_SEGS,
    EPS_DISC,
    EPS_S,
    EPS_V,
    GEOM_EPS,
    HELD_OUT_OFFSET,
    MU,
    OP_A,
    OP_B,
    SNAP_GRID,
    DifficultyDials,
    OperatingPoint,
    TTDParams,
    default_params,
    iter_pilot_dials,
    provisional_fields,
)
from .shapes import (
    Shape,
    ShapeGenParams,
    ShapeLibrary,
    build_library,
    generate_shape,
    generate_shape_retry,
    library_from_json,
    library_to_json,
    sample_p5_area,
    sample_p5b_area,
    shape_from_json,
    shape_to_json,
)

__all__ = [
    "AntipodalPair",
    "BUFFER_QUAD_SEGS",
    "C7Report",
    "CKind",
    "DifficultyDials",
    "EPS_DISC",
    "EPS_S",
    "EPS_V",
    "GEOM_EPS",
    "GeometryError",
    "HELD_OUT_OFFSET",
    "Label",
    "LabelResult",
    "MU",
    "NestResult",
    "NestStatus",
    "NesterConfig",
    "OP_A",
    "OP_B",
    "OpCounter",
    "OperatingPoint",
    "Placement",
    "SNAP_GRID",
    "Shape",
    "ShapeGenParams",
    "ShapeLibrary",
    "TTDParams",
    "Vertices",
    "antipodal_edge_pairs",
    "aspect_ratio",
    "brunn_minkowski_lhs",
    "brunn_minkowski_ok",
    "build_library",
    "convex_decompose",
    "convexity_defect",
    "count_reflex_vertices",
    "default_params",
    "dial_consistency",
    "generate_shape",
    "generate_shape_retry",
    "has_admissible_antipodal_pair",
    "ifp",
    "inflate",
    "inflated_area",
    "inflated_area_approx",
    "interior_disjoint",
    "iter_pilot_dials",
    "label_candidate",
    "library_from_json",
    "library_to_json",
    "min_edge_length",
    "minkowski_sum_convex",
    "nest",
    "nfp",
    "normalize_ccw",
    "occupancy_rule_ok",
    "packing_margin_radius",
    "packs",
    "phi_f",
    "phi_i",
    "phi_occupancy",
    "provisional_fields",
    "reflect",
    "region_vertices",
    "sample_boundary",
    "sample_p5_area",
    "sample_p5b_area",
    "shape_from_json",
    "shape_to_json",
    "signed_area",
    "snap",
    "to_polygon",
    "to_vertices",
    "verify_placements",
    "within_container",
]
